"""WAF and rate-limit state detection.

A host behind a WAF answers differently once it decides it does not like you,
and a scanner that does not notice reports the block pages as findings. Worse,
everything it tested during the blocked window is unreliable, including results
that look clean.

So block, challenge and throttle responses are classified explicitly. The
verification engine treats work done while a host was in that state as
provisional and re-queues it rather than reporting it.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import StrEnum

__all__ = ["WafState", "WafVerdict", "classify_response", "looks_like_challenge"]


class WafState(StrEnum):
    CLEAN = "clean"
    BLOCKED = "blocked"          # the request was refused outright
    CHALLENGED = "challenged"    # a captcha or JS interstitial
    RATE_LIMITED = "rate_limited"
    UNAVAILABLE = "unavailable"  # the origin is struggling


# Body markers, keyed by the vendor they identify. Matched case-insensitively
# against a decoded prefix of the body.
_BODY_MARKERS: tuple[tuple[str, str, WafState], ...] = (
    ("cloudflare", "attention required", WafState.BLOCKED),
    ("cloudflare", "cloudflare ray id", WafState.BLOCKED),
    ("cloudflare", "checking your browser before accessing", WafState.CHALLENGED),
    ("cloudflare", "cf-error-details", WafState.BLOCKED),
    ("akamai", "reference #", WafState.BLOCKED),
    ("akamai", "access denied", WafState.BLOCKED),
    ("imperva", "incapsula incident id", WafState.BLOCKED),
    ("imperva", "powered by imperva", WafState.BLOCKED),
    ("sucuri", "sucuri website firewall", WafState.BLOCKED),
    ("aws", "request blocked", WafState.BLOCKED),
    ("f5", "the requested url was rejected", WafState.BLOCKED),
    ("barracuda", "barracuda", WafState.BLOCKED),
    ("fortinet", "fortigate", WafState.BLOCKED),
    ("wordfence", "generated by wordfence", WafState.BLOCKED),
    ("modsecurity", "mod_security", WafState.BLOCKED),
    ("modsecurity", "not acceptable", WafState.BLOCKED),
    ("generic", "web application firewall", WafState.BLOCKED),
    ("generic", "your request has been blocked", WafState.BLOCKED),
    ("generic", "security policy", WafState.BLOCKED),
    ("generic", "bot detection", WafState.CHALLENGED),
    ("generic", "please enable javascript and cookies", WafState.CHALLENGED),
    ("generic", "rate limit exceeded", WafState.RATE_LIMITED),
    ("generic", "too many requests", WafState.RATE_LIMITED),
)

# Header names that identify the edge, used only to attribute a vendor once a
# block has already been detected. Their presence alone means nothing: plenty of
# healthy sites sit behind a CDN.
_VENDOR_HEADERS: tuple[tuple[str, str], ...] = (
    ("cf-ray", "cloudflare"),
    ("cf-mitigated", "cloudflare"),
    ("x-akamai-transformed", "akamai"),
    ("x-iinfo", "imperva"),
    ("x-sucuri-id", "sucuri"),
    ("x-amzn-waf-action", "aws"),
    ("x-cdn", "generic"),
)

_CAPTCHA_RE = re.compile(
    r"(recaptcha|hcaptcha|turnstile|captcha-delivery|cf-challenge)", re.IGNORECASE
)


@dataclass(frozen=True)
class WafVerdict:
    """What a response says about the host's willingness to be scanned."""

    state: WafState
    vendor: str | None = None
    signal: str | None = None
    retry_after_seconds: float | None = None

    @property
    def obstructed(self) -> bool:
        """True when this response cannot be trusted as a test result."""
        return self.state is not WafState.CLEAN

    @property
    def should_back_off(self) -> bool:
        return self.state in {
            WafState.BLOCKED,
            WafState.CHALLENGED,
            WafState.RATE_LIMITED,
            WafState.UNAVAILABLE,
        }

    def as_dict(self) -> dict:
        return {
            "state": self.state.value,
            "vendor": self.vendor,
            "signal": self.signal,
            "retry_after_seconds": self.retry_after_seconds,
        }


def _vendor_from_headers(headers: dict[str, str]) -> str | None:
    lowered = {key.lower(): value for key, value in headers.items()}
    for header, vendor in _VENDOR_HEADERS:
        if header in lowered:
            return vendor
    server = lowered.get("server", "").lower()
    for token, vendor in (
        ("cloudflare", "cloudflare"),
        ("akamaighost", "akamai"),
        ("awselb", "aws"),
        ("bigip", "f5"),
    ):
        if token in server:
            return vendor
    return None


def _retry_after(headers: dict[str, str]) -> float | None:
    for key, value in headers.items():
        if key.lower() == "retry-after":
            try:
                return float(int(value))
            except (TypeError, ValueError):
                return 30.0  # HTTP-date form; be generous rather than clever
    return None


def looks_like_challenge(body: bytes) -> bool:
    """True when a body carries a captcha or interstitial."""
    return bool(_CAPTCHA_RE.search(body[:20_000].decode("utf-8", errors="replace")))


def classify_response(
    *, status: int, headers: dict[str, str] | None = None, body: bytes = b""
) -> WafVerdict:
    """Classify one response as clean, blocked, challenged, throttled or down.

    Status alone is not enough: a legitimate 403 on a protected admin path is a
    finding, not a WAF block. Body markers are what separate the two, so a status
    in the suspicious range is only treated as obstruction when something in the
    response supports it.
    """
    headers = headers or {}
    vendor = _vendor_from_headers(headers)
    retry_after = _retry_after(headers)
    text = body[:20_000].decode("utf-8", errors="replace").lower()

    # Explicit throttling is unambiguous.
    if status == 429:
        return WafVerdict(
            WafState.RATE_LIMITED, vendor, "HTTP 429", retry_after or 30.0
        )

    for marker_vendor, marker, state in _BODY_MARKERS:
        if marker in text:
            return WafVerdict(
                state,
                vendor or (marker_vendor if marker_vendor != "generic" else None),
                f"body marker: {marker!r}",
                retry_after,
            )

    if _CAPTCHA_RE.search(text):
        return WafVerdict(WafState.CHALLENGED, vendor, "captcha present", retry_after)

    if status in {502, 503, 504, 507, 509}:
        return WafVerdict(WafState.UNAVAILABLE, vendor, f"HTTP {status}", retry_after)

    # A bare 403/406 from a known edge, with a body too small to be a real page,
    # is a block rather than a protected resource.
    if status in {403, 406} and vendor is not None and len(body) < 2000:
        return WafVerdict(
            WafState.BLOCKED, vendor, f"HTTP {status} from {vendor} with a short body",
            retry_after,
        )

    return WafVerdict(WafState.CLEAN, vendor, None, retry_after)
