"""initial schema

Revision ID: 62b896f5b9b2
Revises: 
Create Date: 2026-09-28 16:38:11.233315
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '62b896f5b9b2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('program_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('scope_yaml', sa.Text(), nullable=False),
    sa.Column('authorized_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authorization_date', sa.Date(), nullable=False),
    sa.Column('attestation', sa.Text(), nullable=False),
    sa.Column('authorization_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_program_slug'), ['slug'], unique=True)

    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(length=253), nullable=False),
    sa.Column('kind', sa.Enum('DOMAIN', 'IP', name='assetkind'), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('resolved_values', sa.JSON(), nullable=True),
    sa.Column('cname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('scheme', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('server', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('wildcard_suspect', sa.Boolean(), nullable=False),
    sa.Column('wildcard_cleared_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fingerprint_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fingerprint_simhash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tls_issuer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tls_not_after', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('tls_problem', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_seen', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('last_seen', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('last_scanned_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'host', name='uq_asset_program_host')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_program_id'), ['program_id'], unique=False)
        batch_op.create_index('ix_asset_program_live', ['program_id', 'is_live'], unique=False)

    op.create_table('baseline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(length=253), nullable=False),
    sa.Column('kind', sa.Enum('NOT_FOUND', 'NORMAL', 'ERROR', 'WAF_BLOCK', 'WILDCARD', name='baselinekind'), nullable=False),
    sa.Column('sample_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('simhash', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('length_band', sa.Integer(), nullable=True),
    sa.Column('body_length', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('header_names', sa.JSON(), nullable=True),
    sa.Column('path_scope', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('baseline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baseline_host'), ['host'], unique=False)
        batch_op.create_index('ix_baseline_host_kind', ['program_id', 'host', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_baseline_program_id'), ['program_id'], unique=False)

    op.create_table('scan_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', 'CANCELLED', name='runstatus'), nullable=False),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('stages_requested', sa.JSON(), nullable=True),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('finished_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('requests_made', sa.Integer(), nullable=False),
    sa.Column('dns_queries', sa.Integer(), nullable=False),
    sa.Column('out_of_scope_blocked', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_run_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_run_status'), ['status'], unique=False)

    op.create_table('schedule_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('next_run_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('last_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', 'CANCELLED', name='runstatus'), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'stage', name='uq_schedule_program_stage')
    )
    with op.batch_alter_table('schedule_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_entry_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_entry_program_id'), ['program_id'], unique=False)

    op.create_table('audit_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('scan_run_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(length=253), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('response_bytes', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('matched_rule', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('block_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_entry_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entry_scan_run_id'), ['scan_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entry_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_audit_program_time', ['program_id', 'timestamp'], unique=False)

    op.create_table('endpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('reflected_parameters', sa.JSON(), nullable=True),
    sa.Column('fingerprint_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fingerprint_simhash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_soft_404', sa.Boolean(), nullable=False),
    sa.Column('interesting_score', sa.Float(), nullable=False),
    sa.Column('first_seen', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('last_seen', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'url', 'method', name='uq_endpoint_program_url_method')
    )
    with op.batch_alter_table('endpoint', schema=None) as batch_op:
        batch_op.create_index('ix_endpoint_asset', ['asset_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_endpoint_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_endpoint_program_id'), ['program_id'], unique=False)

    op.create_table('observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('first_seen', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('last_seen', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observation_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index('ix_observation_lookup', ['program_id', 'kind', 'key'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_program_id'), ['program_id'], unique=False)

    op.create_table('stage_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', 'CANCELLED', name='runstatus'), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('finished_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('items_in', sa.Integer(), nullable=False),
    sa.Column('items_out', sa.Integer(), nullable=False),
    sa.Column('items_filtered', sa.Integer(), nullable=False),
    sa.Column('filter_reasons', sa.JSON(), nullable=True),
    sa.Column('tools_used', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('checkpoint', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_run_id', 'stage', name='uq_stage_run_unique')
    )
    with op.batch_alter_table('stage_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_run_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stage_run_scan_run_id'), ['scan_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stage_run_status'), ['status'], unique=False)

    op.create_table('finding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('scan_run_id', sa.Integer(), nullable=True),
    sa.Column('vuln_class', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('tier', sa.Enum('CONFIRMED', 'PROBABLE', 'NEEDS_REVIEW', 'DISCARDED', name='findingtier'), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('discard_reason', sa.Text(), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('reproduced_count', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('tested_while_throttled', sa.Boolean(), nullable=False),
    sa.Column('detector', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('dedup_key', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('affected_hosts', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('triage_status', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('first_seen', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('last_seen', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('verified_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoint.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index('ix_finding_dedup', ['program_id', 'dedup_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_dedup_key'), ['dedup_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_program_id'), ['program_id'], unique=False)
        batch_op.create_index('ix_finding_program_tier', ['program_id', 'tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_scan_run_id'), ['scan_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_tier'), ['tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_vuln_class'), ['vuln_class'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('request_method', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('request_url', sa.Text(), nullable=True),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('response_excerpt', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('curl_command', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_finding_id'), ['finding_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_finding_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_vuln_class'))
        batch_op.drop_index(batch_op.f('ix_finding_tier'))
        batch_op.drop_index(batch_op.f('ix_finding_scan_run_id'))
        batch_op.drop_index('ix_finding_program_tier')
        batch_op.drop_index(batch_op.f('ix_finding_program_id'))
        batch_op.drop_index(batch_op.f('ix_finding_priority'))
        batch_op.drop_index(batch_op.f('ix_finding_endpoint_id'))
        batch_op.drop_index(batch_op.f('ix_finding_dedup_key'))
        batch_op.drop_index('ix_finding_dedup')
        batch_op.drop_index(batch_op.f('ix_finding_asset_id'))

    op.drop_table('finding')
    with op.batch_alter_table('stage_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_run_status'))
        batch_op.drop_index(batch_op.f('ix_stage_run_scan_run_id'))
        batch_op.drop_index(batch_op.f('ix_stage_run_program_id'))

    op.drop_table('stage_run')
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observation_program_id'))
        batch_op.drop_index('ix_observation_lookup')
        batch_op.drop_index(batch_op.f('ix_observation_asset_id'))

    op.drop_table('observation')
    with op.batch_alter_table('endpoint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_endpoint_program_id'))
        batch_op.drop_index(batch_op.f('ix_endpoint_asset_id'))
        batch_op.drop_index('ix_endpoint_asset')

    op.drop_table('endpoint')
    with op.batch_alter_table('audit_entry', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_program_time')
        batch_op.drop_index(batch_op.f('ix_audit_entry_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_entry_scan_run_id'))
        batch_op.drop_index(batch_op.f('ix_audit_entry_program_id'))

    op.drop_table('audit_entry')
    with op.batch_alter_table('schedule_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_entry_program_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_entry_next_run_at'))

    op.drop_table('schedule_entry')
    with op.batch_alter_table('scan_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_run_status'))
        batch_op.drop_index(batch_op.f('ix_scan_run_program_id'))

    op.drop_table('scan_run')
    with op.batch_alter_table('baseline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baseline_program_id'))
        batch_op.drop_index('ix_baseline_host_kind')
        batch_op.drop_index(batch_op.f('ix_baseline_host'))

    op.drop_table('baseline')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index('ix_asset_program_live')
        batch_op.drop_index(batch_op.f('ix_asset_program_id'))
        batch_op.drop_index(batch_op.f('ix_asset_host'))

    op.drop_table('asset')
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_slug'))

    op.drop_table('program')
    # ### end Alembic commands ###
